### ISSUE TITLE
Add Overview

### ISSUE THREAD

**Issue by StickyFloors** [oasis-tcs/oc2arch#10]
Between proposed new Document Conventions section (see #9) and existing 1.5, add Overview section complete with image schematic as it appears in HTTPS spec.

**Comment by dlemire60** [comment]
Following merging PRs #22  and #23, this issue needs to be updated to account for the change to the new OASIS template for the Architecture Spec and the publication of the v1.1 HTTPS specification. Is the issue still relevant? Where is the "image schematic" now?

**Comment by dlemire60** [comment]
@StickyFloors I believe the material you referenced here now appears in [section 2 under the new template](https://github.com/oasis-tcs/openc2-oc2arch/blob/working/oc2arch-v1.0.md#2-overview-of-openc2-architecture).  Can you review and confirm whether this issue can be closed?

**Comment by dlemire60** [comment]
Given material integrated from original OpenC2 specifications in the PRs referenced above, closing this issues.
