### ISSUE TITLE
Add Packet Filter to registry

### ISSUE THREAD

**Issue by alevere** [oasis-tcs/oc2arch#15]
https://docs.oasis-open.org/openc2/ap-pf/v1.0/csd01/ap-pf-v1.0-csd01.html

**Comment by dlemire60** [comment]
I believe this was accomplished in the recent update of the registry and separation of the description from the actual registry.  @alevere / @davaya : do you concur this issue can be closed?

**Comment by Vasileios-Mavroeidis** [comment]
I confirm that it is included in the registry.

**Comment by davaya** [comment]
I concur that it can be closed; the registry (with PF) can be seen at https://github.com/oasis-tcs/openc2-oc2arch/blob/working/namespace-registry.md
