### ISSUE TITLE
Add rationale for action-target structure

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/oc2arch#19]
Section 2 lists "Command" and "Response", then says "The Action and Target components are required."

A more comprehensive description of the design approach would be useful.  Microsoft Powershell (https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands) uses a verb-noun pair for the names of cmdlets, and curates the list of verbs, providing recommendations to developers in order to "ensure consistency between the cmdlets that you create, the cmdlets that are provided by PowerShell, and the cmdlets that are designed by others."

OpenC2 adopted the same design philosophy for the same reasons - the list of actions is built into the language specification, while targets (nouns) are primarily defined by developers.  The architecture document should both:
1) articulate that design philosophy, and
2) when proposing new actions to the LS, seriously consider Powershell conventions in order to maximize commonality when appropriate.

As an example, we have already chosen allow and deny because those verbs are common in network devices.  Powershell uses block and unblock security verbs.  We would not change existing OC2 actions solely for alignment.  But OC2 has start, stop, and restart, which do align with Powershell lifecycle verbs, and if we consider additional actions (suspend, resume) we should align when it makes sense, and avoid non-recommended alternatives (e.g., pause).

**Comment by dlemire60** [comment]
This is interesting information. I agree we should articulate our design philosophy in the architecture spec.

The PowerShell parallel isn't one I'd considered before. Clearly it's got a much longer list of verbs (commands), being a general tool rather than a security-focused one. The lists of "synonyms to avoid is kind of entertaining.  for example:

<html>
<body>


Test (t) | Verifies the operation or consistency of a resource. | Diagnose, Analyze, Salvage, Verify
-- | -- | --



</body>
</html>

**Comment by dlemire60** [comment]
As with Introspection (Issue #49) one reasonable location would be a new section 2.1.3:

- 2.1.1 OpenC2 Command
- 2.1.2 OpenC2 Response
- 2.1.3 _OpenC2 Action-Target Rationale_

The new section 2.1.3 could be the home for a discussion of the rationale for the structure, its relationship to things like Powershell, and the potential to consult Powershell (and others?) as a touchstone if/when new actions are needed.

**Comment by dlemire60** [comment]
This issue was addressed by PR #54 and there is now document content for refinement. Closing the issue.
