### ISSUE TITLE
Update to new OASIS Template

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/oc2arch#20]

**Comment by dlemire60** [comment]
Implementation underway, Working drafts WD01 (final state under original template) and WD02 (unpopulated starter document for new template) have been generated as releases an uploaded to OASIS.

Pull requests #22 and #23 address updating the document headers and placing section 1 content, normative references, and section 2 content into the new template.

**Comment by dlemire60** [comment]
PRs have been merged; closing this issue.
