### ISSUE TITLE
Rename to OpenC2-oc2arch?

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/oc2arch#21]
The other repo's all start with OpenC2 to make for easy filtering/sorting. This is the one exception. Should we rename?

**Comment by dlemire60** [comment]
I would be in favor of that. Having the "one exception" is an inconvenience for those "in the know" but effectively hides the repo from those who are just looking for OpenC2 on GitHub.

**Comment by dlemire60** [comment]
Repository was renamed by OASIS on 12/21/2021.  Closing this issue.
