### ISSUE TITLE
Discuss: Producer / Consumer / Device / Actuator diagrams in 2.2

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/oc2arch#39]
@dlemire submitted these diagrams long ago (PR #4, August 2020) and they were merged, but I don't believe they've ever been discussed. The view the present is influenced by the design of the OpenC2 Integration Framework (OIF).  I think a meaningful discussion of these diagrams is appropriate, including consideration of whether the discussion of them is adequate and additional options are needed. 

There's a related, lesser question regarding the presentation of the material: should the examples be separated into individual figures with a more extended discussion of each, perhaps as subsections of 2.3.

Finally, do we need a fourth configuration for when the Consumer is also a Producer (i.e., the interface to the managed devices behind the consumer is explicitly OpenC2)?

**Comment by davaya** [comment]
In the diagrams, "Multiple Actuator Device" should be replaced by "Multiple Function Device" or "Multiple Profile Device".  The "actuator" returned by a "query profiles" response or specified in the "actuator" field of a command identifies an actuator profile, i.e., a function, not a device.

**Comment by dlemire60** [comment]
After considering a bunch of factors, I'm going to move ahead with splitting the current figure into 3 individual ones, and add the fourth I proposed above, then work on a slightly more expanded discussion of the four configurations.

**Comment by dlemire60** [comment]
This issue was addressed by PR #53 and there is now content in the document for discussion and refinement. Closing the issue.
