### ISSUE TITLE
Clarification for profile unique names

### ISSUE THREAD

**Issue by Vasileios-Mavroeidis** [oasis-tcs/oc2arch#46]
I assume that it has been discussed multiple times already, but why we don't follow the OASIS guidelines for creating URIs? https://docs.oasis-open.org/specGuidelines/namingGuidelines/resourceNaming.html

**Comment by dlemire60** [comment]
I think I need a pointer to where in the specification this comment is aimed, and how you think we aren't following the guidelines. Also, recall that we have a section in the Documentation Norms in the TC Operations repo that speaks to [naming work products](https://github.com/oasis-tcs/openc2-tc-ops/blob/main/Documentation-Norms.md#42-assign-work-product-name).

**Comment by Vasileios-Mavroeidis** [comment]
The namespace names captured in the registry.

"URIs for OASIS resources, as well as for HTTP scheme namespace URIs, should begin with the [exact, case-specific] 27 characters: http://docs.oasis-open.org/ unless specified otherwise by the OASIS TC Administration as an allowable exception"

**Comment by dlemire60** [comment]
Ah, OK.  We should fix that, but I suspect it's less of a deliberate choice and more of an oversight. So, we 

- have:  http://oasis-open.org/openc2/lang/v1.0, but 
- should have:  http://docs.oasis-open.org/openc2/lang/v1.0

etc., etc. Right?

**Comment by davaya** [comment]
The rationale was that namespaces were not information resources (nothing can be downloaded from the namespace URI), but I was unaware that OASIS also recommends the same prefix for HTTP scheme namespaces.  Since they do, I will fix the registry to follow the guidelines.

The relevant text is:

> In order to avoid creating collision/confusion through semantic overloading at a point where an HTTP schema XML Namespace URI could be mistaken for a regular directory URI, or vice versa, Namespace URIs and associated names (named properties, functions, dialects, faults, actions, other message types as [non-information resources](http://docs.oasis-open.org/specGuidelines/namingGuidelines/resourceNamingCommentaryV08.html#information-resources)) are to use a reserved path structure containing the literal element /ns/. For any [Type 1](http://docs.oasis-open.org/specGuidelines/namingGuidelines/resourceNamingCommentaryV08.html#slashTypeURI) or [Type 3](http://docs.oasis-open.org/specGuidelines/namingGuidelines/resourceNamingCommentaryV08.html#simpleTypeURI) namespace URI terminating in foo/ or foo (e.g., for http://docs.oasis-open.org/ns/<ShortName\>/foo/ or http://docs.oasis-open.org/ns/<ShortName\>/foo), [no URIs should be created](http://docs.oasis-open.org/specGuidelines/namingGuidelines/resourceNamingCommentaryV08.html#uri-overloading) for information resources matching "*" in http://docs.oasis-open.org/ns/<ShortName\>/foo/*. We will not create a folder/directory foo on the file system, nor locate any content in (an imaginary) directory foo/, because the path containing /ns/ is reserved for the declared namespace and related non-information resources.

... so the OpenC2 namespaces will be `http://docs.oasis-open.org/ns/openc2/lang/v1.0` etc.

**Comment by dlemire60** [comment]
We agreed on namespace conventions at the end of Nov 2023 and have merged multiple PRs related to namespace definitions and management:

- AS: PR #92 - update registry namespaces
- AS: PR #93 - Appendix F update
- LS: [PR #432](https://github.com/oasis-tcs/openc2-oc2ls/pull/432) - update link to NS registry

I believe this issue can be closed. Adding label.

**Comment by dlemire60** [comment]
Discussed at 14 Feb 2024 working meeting, and closing approved.
