### ISSUE TITLE
Add Architecture doc to section 1.0

### ISSUE THREAD

**Issue by StickyFloors** [oasis-tcs/oc2arch#6]
Language in section 1.0 is a direct copy/paste lift from the language spec. It should be updated to reflect position in architecture doc.

**Comment by StickyFloors** [comment]
This involves multiple sub-issues (#7, #9, #10)

**Comment by dlemire60** [comment]
The title concern has been addressed and the Architecture Spec is now the first document cited in 1.0. So #6 is addressed. Closing this issue.
