### ISSUE TITLE
Readme and published v master

### ISSUE THREAD

**Issue by alevere** [oasis-tcs/oc2arch#65]
Should update the readme to reflect the published branch:

"The Master branch contains TC-approved [Committee Specification](https://www.oasis-open.org/policies-guidelines/oasis-defined-terms-2018-05-22#dCommitteeSpec) (CS) or [OASIS Standard](https://www.oasis-open.org/policies-guidelines/oasis-defined-terms-2018-05-22#dOASISstandard) versions of the work product. Until the first CS is approved, the Master branch will not contain a complete version of the work product."

**Comment by dlemire60** [comment]
This only applies to the working branch README, and was addressed by PR #66

README updated, so closing this issue.
