### ISSUE TITLE
1.5 Update 

### ISSUE THREAD

**Issue by StickyFloors** [oasis-tcs/oc2arch#7]
First paragraph of section 1.5: Goals needs to change in reflection of differences between language spec and architecture document.

**Comment by dlemire60** [comment]
With the reorg from PR #22 section 1.5 now longer exists. Correct action at this point is to grab the old 1.5 text from the [original template version](https://github.com/oasis-tcs/openc2-oc2arch/blob/working/original-template/oc2arch-v1.0-csprd01.md), determine where it belongs in the new outline, insert it there and update to reflect the purposes of this document.

**Comment by dlemire60** [comment]
This issue is addressed with PR #47

**Comment by dlemire60** [comment]
Based on the approval and merging of PR #47 I am closing this issue.
