### ISSUE TITLE
Add Document Conventions 

### ISSUE THREAD

**Issue by StickyFloors** [oasis-tcs/oc2arch#9]
After current 1.4 and before current 1.5, boiler-plate section titled "Document Conventions" should be inserted to reflect OASIS best practices.

**Comment by dlemire60** [comment]
This should be revisited in light of PRs #22 and #23 -- is the location referenced still the right one?

**Comment by dlemire60** [comment]
Should now go to section 1.2.3.

**Comment by dlemire60** [comment]
Given the nature of this specification as an over-arching description of OpenC2, we may not need this section.

**Comment by dlemire60** [comment]
Recommend closing this issue. Except for one JSON command / response example, the AS doesn't contain any materials where conventions need to be defined and explained.

**Comment by dlemire60** [comment]
Discussed at 14 Feb 2024 working meeting, and closing approved.
